<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DesafiosSeeder extends Seeder
{
    public function run()
    {
        DB::table('desafios')->insert([
            [
                'titulo' => 'Tomar 8 vasos de agua',
                'descripcion' => 'Mantén tu cuerpo hidratado durante el día.',
                'tipo_desafio' => 'diario',
                'categoria' => 'hidratacion',
                'objetivo_valor' => 8,
                'unidad_medida' => 'vasos',
                'puntos_recompensa' => 10,
                'fecha_inicio' => Carbon::today()->subDay(),
                'fecha_fin' => Carbon::today()->addDays(5),
                'activo' => true,
                'dificultad' => 1,
                'icono' => 'agua.png',
                'objetivos_relacionados' => json_encode(['Perder peso', 'Mejorar salud cardiovascular']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Dormir al menos 7 horas',
                'descripcion' => 'Asegúrate de dormir bien cada noche.',
                'tipo_desafio' => 'diario',
                'categoria' => 'descanso',
                'objetivo_valor' => 7,
                'unidad_medida' => 'horas',
                'puntos_recompensa' => 12,
                'fecha_inicio' => Carbon::today()->subDay(),
                'fecha_fin' => Carbon::today()->addDays(7),
                'activo' => true,
                'dificultad' => 1,
                'icono' => 'sueño.png',
                'objetivos_relacionados' => json_encode(['Reducir estrés', 'Perder peso']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Entrenamiento de fuerza 3 veces',
                'descripcion' => 'Haz ejercicios de fuerza como flexiones o sentadillas.',
                'tipo_desafio' => 'semanal',
                'categoria' => 'actividad',
                'objetivo_valor' => 3,
                'unidad_medida' => 'veces',
                'puntos_recompensa' => 25,
                'fecha_inicio' => Carbon::today()->subDay(),
                'fecha_fin' => Carbon::today()->addDays(7),
                'activo' => true,
                'dificultad' => 2,
                'icono' => 'fuerza.png',
                'objetivos_relacionados' => json_encode(['Aumentar fuerza muscular', 'Perder peso']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Meditar 10 minutos diarios',
                'descripcion' => 'Dedica tiempo para relajarte y despejar la mente.',
                'tipo_desafio' => 'diario',
                'categoria' => 'bienestar',
                'objetivo_valor' => 10,
                'unidad_medida' => 'minutos',
                'puntos_recompensa' => 10,
                'fecha_inicio' => Carbon::today()->subDay(),
                'fecha_fin' => Carbon::today()->addDays(5),
                'activo' => true,
                'dificultad' => 1,
                'icono' => 'meditacion.png',
                'objetivos_relacionados' => json_encode(['Reducir estrés']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Evitar azúcar por 3 días',
                'descripcion' => 'No consumas azúcar refinada durante 3 días.',
                'tipo_desafio' => 'semanal',
                'categoria' => 'alimentacion',
                'objetivo_valor' => 3,
                'unidad_medida' => 'días',
                'puntos_recompensa' => 18,
                'fecha_inicio' => Carbon::today()->subDay(),
                'fecha_fin' => Carbon::today()->addDays(6),
                'activo' => true,
                'dificultad' => 2,
                'icono' => 'noazucar.png',
                'objetivos_relacionados' => json_encode(['Perder peso', 'Mejorar salud cardiovascular']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Estiramientos matutinos',
                'descripcion' => 'Haz una rutina de estiramientos por la mañana.',
                'tipo_desafio' => 'diario',
                'categoria' => 'flexibilidad',
                'objetivo_valor' => 1,
                'unidad_medida' => 'sesión',
                'puntos_recompensa' => 10,
                'fecha_inicio' => Carbon::today()->subDay(),
                'fecha_fin' => Carbon::today()->addDays(3),
                'activo' => true,
                'dificultad' => 1,
                'icono' => 'estiramiento.png',
                'objetivos_relacionados' => json_encode(['Mejorar flexibilidad', 'Reducir estrés']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Realiza una caminata larga de 60 min',
                'descripcion' => 'Camina una hora sin pausas intensas al aire libre.',
                'tipo_desafio' => 'semanal',
                'categoria' => 'actividad',
                'objetivo_valor' => 60,
                'unidad_medida' => 'minutos',
                'puntos_recompensa' => 22,
                'fecha_inicio' => Carbon::today()->subDay(),
                'fecha_fin' => Carbon::today()->addDays(7),
                'activo' => true,
                'dificultad' => 2,
                'icono' => 'caminar.png',
                'objetivos_relacionados' => json_encode(['Mejorar salud cardiovascular', 'Perder peso']),
                'created_at' => now(),
                'updated_at' => now(),
            ]

            // puedes seguir agregando más desafíos diarios/semanales
        ]);
    }
}
