<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TallerRecreativoSeeder extends Seeder
{
    public function run(): void
    {
        $talleres = [
            // === EJERCICIO Y FITNESS ===
            [
                'nombre' => 'Yoga para Principiantes',
                'descripcion' => 'Inicia tu práctica de yoga con posturas básicas y técnicas de respiración',
                'instructor' => 'Ana María González',
                'categoria' => 'Ejercicio',
                'duracion_minutos' => 60,
                'nivel_dificultad' => 1,
                'cupo_maximo' => 15,
                'costo' => 0.00,
                'ubicacion' => 'Sala de Yoga, Piso 2',
                'fecha_inicio' => Carbon::tomorrow()->setTime(7, 0),
                'fecha_fin' => Carbon::tomorrow()->setTime(8, 0),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Traer mat de yoga o toalla',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Pilates Intermedio',
                'descripcion' => 'Fortalece tu core y mejora tu postura con ejercicios de pilates',
                'instructor' => 'Laura Martínez',
                'categoria' => 'Ejercicio',
                'duracion_minutos' => 50,
                'nivel_dificultad' => 2,
                'cupo_maximo' => 12,
                'costo' => 5.00,
                'ubicacion' => 'Sala de Pilates, Piso 1',
                'fecha_inicio' => Carbon::tomorrow()->setTime(8, 30),
                'fecha_fin' => Carbon::tomorrow()->setTime(9, 20),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Ropa deportiva cómoda',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Cardio HIIT',
                'descripcion' => 'Entrenamiento de alta intensidad para quemar calorías y mejorar resistencia',
                'instructor' => 'Carlos Ruiz',
                'categoria' => 'Ejercicio',
                'duracion_minutos' => 45,
                'nivel_dificultad' => 3,
                'cupo_maximo' => 20,
                'costo' => 0.00,
                'ubicacion' => 'Gimnasio Principal',
                'fecha_inicio' => Carbon::tomorrow()->setTime(18, 0),
                'fecha_fin' => Carbon::tomorrow()->setTime(18, 45),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Toalla y botella de agua',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Aqua Aeróbicos',
                'descripcion' => 'Ejercicios de bajo impacto en el agua para todas las edades',
                'instructor' => 'Patricia Vega',
                'categoria' => 'Ejercicio',
                'duracion_minutos' => 60,
                'nivel_dificultad' => 1,
                'cupo_maximo' => 15,
                'costo' => 8.00,
                'ubicacion' => 'Piscina Techada',
                'fecha_inicio' => Carbon::tomorrow()->setTime(16, 0),
                'fecha_fin' => Carbon::tomorrow()->setTime(17, 0),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Traje de baño y toalla',
                'created_at' => now(),
                'updated_at' => now()
            ],

            // === ALIMENTACIÓN Y NUTRICIÓN ===
            [
                'nombre' => 'Cocina Saludable Vegana',
                'descripcion' => 'Aprende a preparar deliciosas comidas veganas nutritivas y balanceadas',
                'instructor' => 'Chef Elena Morales',
                'categoria' => 'Alimentación',
                'duracion_minutos' => 90,
                'nivel_dificultad' => 2,
                'cupo_maximo' => 12,
                'costo' => 15.00,
                'ubicacion' => 'Cocina Didáctica, Piso 1',
                'fecha_inicio' => Carbon::tomorrow()->setTime(10, 0),
                'fecha_fin' => Carbon::tomorrow()->setTime(11, 30),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Traer delantal',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Smoothies y Jugos Detox',
                'descripcion' => 'Crea bebidas nutritivas para desintoxicar y energizar tu cuerpo',
                'instructor' => 'Nutri. Sofia López',
                'categoria' => 'Alimentación',
                'duracion_minutos' => 60,
                'nivel_dificultad' => 1,
                'cupo_maximo' => 18,
                'costo' => 10.00,
                'ubicacion' => 'Laboratorio de Nutrición',
                'fecha_inicio' => Carbon::tomorrow()->setTime(15, 0),
                'fecha_fin' => Carbon::tomorrow()->setTime(16, 0),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Ninguno - ingredientes incluidos',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Nutrición Deportiva',
                'descripcion' => 'Aprende qué comer antes, durante y después del ejercicio',
                'instructor' => 'Dr. Miguel Fernández',
                'categoria' => 'Alimentación',
                'duracion_minutos' => 75,
                'nivel_dificultad' => 2,
                'cupo_maximo' => 25,
                'costo' => 0.00,
                'ubicacion' => 'Aula Magna',
                'fecha_inicio' => Carbon::tomorrow()->setTime(19, 0),
                'fecha_fin' => Carbon::tomorrow()->setTime(20, 15),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Cuaderno para tomar notas',
                'created_at' => now(),
                'updated_at' => now()
            ],

            // === DÍA 2 - MÁS EJERCICIOS ===
            [
                'nombre' => 'Stretching y Flexibilidad',
                'descripcion' => 'Mejora tu flexibilidad y reduce tensiones musculares',
                'instructor' => 'Kinesiólogo Juan Pérez',
                'categoria' => 'Ejercicio',
                'duracion_minutos' => 45,
                'nivel_dificultad' => 1,
                'cupo_maximo' => 20,
                'costo' => 0.00,
                'ubicacion' => 'Sala de Rehabilitación',
                'fecha_inicio' => Carbon::tomorrow()->addDay()->setTime(7, 30),
                'fecha_fin' => Carbon::tomorrow()->addDay()->setTime(8, 15),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Mat y ropa cómoda',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Entrenamiento Funcional',
                'descripcion' => 'Ejercicios que mejoran tus actividades de la vida diaria',
                'instructor' => 'Trainer Roberto Silva',
                'categoria' => 'Ejercicio',
                'duracion_minutos' => 60,
                'nivel_dificultad' => 2,
                'cupo_maximo' => 16,
                'costo' => 5.00,
                'ubicacion' => 'Gimnasio Funcional',
                'fecha_inicio' => Carbon::tomorrow()->addDay()->setTime(9, 0),
                'fecha_fin' => Carbon::tomorrow()->addDay()->setTime(10, 0),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Zapatillas deportivas',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Natación para Adultos',
                'descripcion' => 'Aprende técnicas de natación o perfecciona tu estilo',
                'instructor' => 'Coach Marina Castillo',
                'categoria' => 'Ejercicio',
                'duracion_minutos' => 60,
                'nivel_dificultad' => 2,
                'cupo_maximo' => 8,
                'costo' => 12.00,
                'ubicacion' => 'Piscina Olímpica',
                'fecha_inicio' => Carbon::tomorrow()->addDay()->setTime(11, 0),
                'fecha_fin' => Carbon::tomorrow()->addDay()->setTime(12, 0),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Traje de baño, gorro y antiparras',
                'created_at' => now(),
                'updated_at' => now()
            ],

            // === BIENESTAR Y SALUD MENTAL ===
            [
                'nombre' => 'Meditación Mindfulness',
                'descripcion' => 'Practica la atención plena y reduce el estrés diario',
                'instructor' => 'Terapeuta Laura Fernández',
                'categoria' => 'Bienestar',
                'duracion_minutos' => 45,
                'nivel_dificultad' => 1,
                'cupo_maximo' => 25,
                'costo' => 0.00,
                'ubicacion' => 'Sala de Meditación, Piso 1',
                'fecha_inicio' => Carbon::tomorrow()->addDay()->setTime(16, 0),
                'fecha_fin' => Carbon::tomorrow()->addDay()->setTime(16, 45),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Ropa cómoda',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Técnicas de Respiración',
                'descripcion' => 'Aprende ejercicios de respiración para el manejo del estrés',
                'instructor' => 'Dra. Carmen Ruiz',
                'categoria' => 'Bienestar',
                'duracion_minutos' => 30,
                'nivel_dificultad' => 1,
                'cupo_maximo' => 30,
                'costo' => 0.00,
                'ubicacion' => 'Jardín Zen',
                'fecha_inicio' => Carbon::tomorrow()->addDay()->setTime(17, 30),
                'fecha_fin' => Carbon::tomorrow()->addDay()->setTime(18, 0),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Ninguno',
                'created_at' => now(),
                'updated_at' => now()
            ],

            // === MÁS ALIMENTACIÓN ===
            [
                'nombre' => 'Meal Prep Saludable',
                'descripcion' => 'Planifica y prepara comidas saludables para toda la semana',
                'instructor' => 'Chef Nutritivo Andrea Torres',
                'categoria' => 'Alimentación',
                'duracion_minutos' => 120,
                'nivel_dificultad' => 2,
                'cupo_maximo' => 10,
                'costo' => 20.00,
                'ubicacion' => 'Cocina Industrial',
                'fecha_inicio' => Carbon::tomorrow()->addDay()->setTime(14, 0),
                'fecha_fin' => Carbon::tomorrow()->addDay()->setTime(16, 0),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Contenedores para llevar comida',
                'created_at' => now(),
                'updated_at' => now()
            ],

            // === DÍA 3 - MÁS VARIEDAD ===
            [
                'nombre' => 'Yoga Terapéutico',
                'descripcion' => 'Yoga especializado para aliviar dolores de espalda y cuello',
                'instructor' => 'Terapeuta Yoga María Santos',
                'categoria' => 'Ejercicio',
                'duracion_minutos' => 75,
                'nivel_dificultad' => 1,
                'cupo_maximo' => 12,
                'costo' => 8.00,
                'ubicacion' => 'Sala de Terapias',
                'fecha_inicio' => Carbon::tomorrow()->addDays(2)->setTime(9, 0),
                'fecha_fin' => Carbon::tomorrow()->addDays(2)->setTime(10, 15),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Mat de yoga',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Zumba Fitness',
                'descripcion' => 'Baila y quema calorías con ritmos latinos divertidos',
                'instructor' => 'Instructora Salsa Gabriela Mendez',
                'categoria' => 'Ejercicio',
                'duracion_minutos' => 60,
                'nivel_dificultad' => 2,
                'cupo_maximo' => 25,
                'costo' => 0.00,
                'ubicacion' => 'Salón de Danza',
                'fecha_inicio' => Carbon::tomorrow()->addDays(2)->setTime(18, 30),
                'fecha_fin' => Carbon::tomorrow()->addDays(2)->setTime(19, 30),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Zapatillas deportivas y toalla',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Alimentación Consciente',
                'descripcion' => 'Desarrolla una relación saludable con la comida y controla la ansiedad',
                'instructor' => 'Psicóloga Nutricional Ana Jiménez',
                'categoria' => 'Alimentación',
                'duracion_minutos' => 90,
                'nivel_dificultad' => 1,
                'cupo_maximo' => 15,
                'costo' => 12.00,
                'ubicacion' => 'Sala de Conferencias',
                'fecha_inicio' => Carbon::tomorrow()->addDays(2)->setTime(15, 0),
                'fecha_fin' => Carbon::tomorrow()->addDays(2)->setTime(16, 30),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Cuaderno personal',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Caminata Saludable',
                'descripcion' => 'Ejercicio cardiovascular suave en grupo al aire libre',
                'instructor' => 'Kinesiólogo Diego Vargas',
                'categoria' => 'Ejercicio',
                'duracion_minutos' => 45,
                'nivel_dificultad' => 1,
                'cupo_maximo' => 30,
                'costo' => 0.00,
                'ubicacion' => 'Parque Central (punto de encuentro: recepción)',
                'fecha_inicio' => Carbon::tomorrow()->addDays(2)->setTime(7, 0),
                'fecha_fin' => Carbon::tomorrow()->addDays(2)->setTime(7, 45),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Zapatillas cómodas y botella de agua',
                'created_at' => now(),
                'updated_at' => now()
            ],

            // === DÍA 4 - TALLERES ESPECIALIZADOS ===
            [
                'nombre' => 'Crossfit para Principiantes',
                'descripcion' => 'Introducción al crossfit con movimientos básicos y seguros',
                'instructor' => 'Coach Crossfit Pedro Ramírez',
                'categoria' => 'Ejercicio',
                'duracion_minutos' => 60,
                'nivel_dificultad' => 2,
                'cupo_maximo' => 12,
                'costo' => 10.00,
                'ubicacion' => 'Box de Crossfit',
                'fecha_inicio' => Carbon::tomorrow()->addDays(3)->setTime(17, 0),
                'fecha_fin' => Carbon::tomorrow()->addDays(3)->setTime(18, 0),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Certificado médico y experiencia básica en ejercicio',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Cocina sin Gluten',
                'descripcion' => 'Recetas deliciosas y nutritivas para personas celíacas',
                'instructor' => 'Chef Especialista Luis Herrera',
                'categoria' => 'Alimentación',
                'duracion_minutos' => 100,
                'nivel_dificultad' => 2,
                'cupo_maximo' => 10,
                'costo' => 18.00,
                'ubicacion' => 'Cocina Especializada',
                'fecha_inicio' => Carbon::tomorrow()->addDays(3)->setTime(11, 0),
                'fecha_fin' => Carbon::tomorrow()->addDays(3)->setTime(12, 40),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Delantal y recipientes para llevar',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Relajación y Manejo del Estrés',
                'descripcion' => 'Técnicas de relajación muscular progresiva y visualización',
                'instructor' => 'Psicóloga Clínica Mónica Paz',
                'categoria' => 'Bienestar',
                'duracion_minutos' => 60,
                'nivel_dificultad' => 1,
                'cupo_maximo' => 20,
                'costo' => 5.00,
                'ubicacion' => 'Sala de Relajación',
                'fecha_inicio' => Carbon::tomorrow()->addDays(3)->setTime(19, 0),
                'fecha_fin' => Carbon::tomorrow()->addDays(3)->setTime(20, 0),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Ropa muy cómoda y manta personal',
                'created_at' => now(),
                'updated_at' => now()
            ],

            // === DÍA 5 - FINES DE SEMANA ===
            [
                'nombre' => 'Tai Chi en el Parque',
                'descripcion' => 'Arte marcial suave que combina movimiento, respiración y meditación',
                'instructor' => 'Maestro Tai Chi Chen Wei',
                'categoria' => 'Ejercicio',
                'duracion_minutos' => 90,
                'nivel_dificultad' => 1,
                'cupo_maximo' => 25,
                'costo' => 0.00,
                'ubicacion' => 'Jardín Zen Exterior',
                'fecha_inicio' => Carbon::tomorrow()->addDays(4)->setTime(8, 0),
                'fecha_fin' => Carbon::tomorrow()->addDays(4)->setTime(9, 30),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Ropa cómoda que permita movimiento',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Hidratación y Salud',
                'descripcion' => 'La importancia del agua y cómo mantenerse correctamente hidratado',
                'instructor' => 'Nutri. Especialista Carla Montoya',
                'categoria' => 'Alimentación',
                'duracion_minutos' => 45,
                'nivel_dificultad' => 1,
                'cupo_maximo' => 40,
                'costo' => 0.00,
                'ubicacion' => 'Auditorio Principal',
                'fecha_inicio' => Carbon::tomorrow()->addDays(4)->setTime(16, 0),
                'fecha_fin' => Carbon::tomorrow()->addDays(4)->setTime(16, 45),
                'activo' => true,
                'imagen_url' => 'https://via.placeholder.com/300x200',
                'requisitos' => 'Botella de agua personal',
                'created_at' => now(),
                'updated_at' => now()
            ]
        ];

        foreach ($talleres as $taller) {
            DB::table('talleres_recreativos')->insert($taller);
        }
    }
} 